# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelPackages = pkgs.linuxPackages_latest;

    initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0ce2a875-f175-438a-ba3e-b31f8616ff0b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-895cdf01-0d68-4495-badb-50ddd7e347d6".device = "/dev/disk/by-uuid/895cdf01-0d68-4495-badb-50ddd7e347d6";
  boot.initrd.luks.devices."luks-80218ca6-3371-4bd3-9010-c9b45ddb6c74".device = "/dev/disk/by-uuid/80218ca6-3371-4bd3-9010-c9b45ddb6c74";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6635-3AD2";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cafa49a9-c9d2-472e-b858-3bc2cf886ab9"; }
    ];

  hardware = {
    pulseaudio.enable = false;
    
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
  };
}
